# Generated by Django 2.2.3 on 2019-09-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstable',
            old_name='Cust_Name',
            new_name='FullName',
        ),
    ]
