# Generated by Django 2.2.3 on 2019-09-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0002_auto_20190914_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Account_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Curr_Balance', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AccountsTable',
        ),
    ]
