# Generated by Django 2.2.3 on 2019-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0003_auto_20190914_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='user@lenzbank.com', max_length=100),
        ),
    ]
